// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Treinamento.Web.Data;

#nullable disable

namespace Treinamento.Web.Migrations
{
    [DbContext(typeof(AppDataContext))]
    partial class AppDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("Treinamento.Web.Models.Informacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LinguagemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LinguagemId");

                    b.ToTable("Informacoes");
                });

            modelBuilder.Entity("Treinamento.Web.Models.Linguagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Linguagens");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Java"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "C#"
                        });
                });

            modelBuilder.Entity("Treinamento.Web.Models.Informacao", b =>
                {
                    b.HasOne("Treinamento.Web.Models.Linguagem", "Linguagem")
                        .WithMany("Informacoes")
                        .HasForeignKey("LinguagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Linguagem");
                });

            modelBuilder.Entity("Treinamento.Web.Models.Linguagem", b =>
                {
                    b.Navigation("Informacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
